name: mstk
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - numpy
  - pandas
  - rdkit
  - openmm
  - mdtraj
  - chemfiles-lib=0.10.2
  - chemfiles-python=0.10.2
  - scipy
  - scikit-learn
  - pymbar=3.1
